---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root

  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        bar:
          - listen 8080
          - location / { try_files $uri $uri/ /index.html; }
          - location /images/ { try_files $uri $uri/ /index.html; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for